### ISSUE TITLE
Username requierd?

### ISSUE THREAD

**Issue by karlholst** [LukeSkywalker92/MMM-Globe#3]
When I execute git clone... It stops and ask for username and password? I can wright in username, but not my password?

**Comment by LukeSkywalker92** [comment]
Can you please show the command you're using to clone the repo?

**Comment by karlholst** [comment]
@LukeSkywalker92 Nvm, I did it! :) Looks totaly awsome! thanks mate

**Comment by jfisher446** [comment]
Note: This prompt appears when a user leaves the '.' at the end of the clone command. Most likely due to a bad copy/paste job.

**Comment by Chris1971** [comment]
Are you able to update MMM Globe, that the pics on the new server EUMETSAT can be displayed?
